
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (1,'Torino',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (2,'Vercelli',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (3,'Novara',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (4,'Cuneo',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (5,'Asti',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (6,'Alessandria',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (7,'Valle d\'Aosta / Vallée d\'Aoste',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (8,'Imperia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (9,'Savona',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (10,'Genova',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (11,'La Spezia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (12,'Varese',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (13,'Como',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (14,'Sondrio',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (15,'Milano',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (16,'Bergamo',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (17,'Brescia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (18,'Pavia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (19,'Cremona',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (20,'Mantova',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (21,'Bolzano / Bozen',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (22,'Trento',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (23,'Verona',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (24,'Vicenza',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (25,'Belluno',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (26,'Treviso',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (27,'Venezia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (28,'Padova',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (29,'Rovigo',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (30,'Udine',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (31,'Gorizia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (32,'Trieste',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (33,'Piacenza',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (34,'Parma',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (35,'Reggio nell\'Emilia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (36,'Modena',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (37,'Bologna',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (38,'Ferrara',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (39,'Ravenna',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (40,'Forlì-Cesena',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (41,'Pesaro e Urbino',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (42,'Ancona',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (43,'Macerata',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (44,'Ascoli Piceno',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (45,'Massa-Carrara',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (46,'Lucca',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (47,'Pistoia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (48,'Firenze',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (49,'Livorno',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (50,'Pisa',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (51,'Arezzo',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (52,'Siena',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (53,'Grosseto',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (54,'Perugia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (55,'Terni',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (56,'Viterbo',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (57,'Rieti',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (58,'Roma',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (59,'Latina',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (60,'Frosinone',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (61,'Caserta',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (62,'Benevento',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (63,'Napoli',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (64,'Avellino',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (65,'Salerno',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (66,'L\'Aquila',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (67,'Teramo',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (68,'Pescara',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (69,'Chieti',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (70,'Campobasso',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (71,'Foggia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (72,'Bari',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (73,'Taranto',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (74,'Brindisi',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (75,'Lecce',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (76,'Potenza',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (77,'Matera',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (78,'Cosenza',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (79,'Catanzaro',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (80,'Reggio di Calabria',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (81,'Trapani',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (82,'Palermo',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (83,'Messina',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (84,'Agrigento',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (85,'Caltanissetta',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (86,'Enna',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (87,'Catania',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (88,'Ragusa',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (89,'Siracusa',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (90,'Sassari',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (91,'Nuoro',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (92,'Cagliari',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (93,'Pordenone',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (94,'Isernia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (95,'Oristano',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (96,'Biella',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (97,'Lecco',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (98,'Lodi',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (99,'Rimini',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (100,'Prato',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (101,'Crotone',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (102,'Vibo Valentia',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (103,'Verbano-Cusio-Ossola',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (104,'Olbia-Tempio',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (105,'Ogliastra',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (106,'Medio Campidano',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (107,'Carbonia-Iglesias',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (108,'Monza e della Brianza',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (109,'Fermo',NULL,1,NULL,NULL);
INSERT INTO `city` (`id`,`name`,`postal_code`,`country_id`,`postalCode`,`countryId`) VALUES (110,'Barletta-Andria-Trani',NULL,1,NULL,NULL);
