
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (1,'Vans','Black','Inspired by Vans Classic Old Skool, the Ward is a low top, vulcanized lace up style with Vans signature side stripe, a round toe, padded collar for extra comfort, a smooth Lining and a cushioning insole.','Vans Old Skool',NULL,70,1,'36',NULL,NULL,'shoes','/assets/img/shoes.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (2,'Feltrinelli','','The Big Book of Dinosaurs is a comprehensive anthology of all things prehistoric. Covering the Triassic, Jurassic and Cretaceous periods, it offers a clear and simple visual introduction to the weirdest, smallest and scariest dinosaurs of all time. ','The big book of dinosaurs',NULL,20,1,'100 pages',NULL,NULL,'book','/assets/img/book.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (3,'Vans','Black','Inspired by Vans Classic Old Skool, the Ward is a low top, vulcanized lace up style with Vans signature side stripe, a round toe, padded collar for extra comfort, a smooth Lining and a cushioning insole.','Test shoes',NULL,87,1,'38',NULL,NULL,'shoes','/assets/img/shoes.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (4,'Swarovski','White','Swarovski necklace used only once','Swarovski Sunshine',NULL,201,1,'15',NULL,NULL,'accessories','/assets/img/aa.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (5,'Pandora','Gold','Pandora necklace never used','Pandora Love',NULL,100,1,NULL,NULL,NULL,'accessories','/assets/img/accesories.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (6,'Vans','Black','Black hoodie by Vans','Hoodie',NULL,50,1,'M',NULL,NULL,'clothes','/assets/img/clothes.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (8,'HP','Silver','Intel Core i3-1115G4 (Frequenza Di Base 3,0Ghz, Fino A 4,1Ghz Con Tecnologia Intel Turbo Boost, 6MB Di Cache L3, 2Core), Monitor Da 15.6\" Antiriflesso Hd (1920x1080) IPS, bordi sottili, antiriflesso, Ram :8Gb, Ddr4-Sdram - Ssd PcIe Nvme M.2 Da 256Gb ','HP pavillion',NULL,600,1,NULL,NULL,NULL,'technology','/assets/img/tecnology.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (9,'Apple','Silver/Black','Processore Intel \"Core i5\" da 2,7 GHz \"Broadwell\" da 2,7 GHz un 3 MB di cache di livello 3 condivisa, 8 GB di SDRAM LPDDR3 a 1866 MHz integrata, 512 GB di memoria flash basata su PCIe a 4 corsie Intel Iris Graphics 6100 integrato','Macbook Pro',NULL,1200,1,NULL,NULL,NULL,'technology','/assets/img/product01.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (10,'Apple','Silver/Black','Processore Intel \"Core i7\" da 2,7 GHz \"Broadwell\" da 2,7 GHz un 4 MB di cache di livello 3 condivisa, 16 GB di SDRAM LPDDR3 a 1866 MHz integrata, 512 GB di memoria flash basata su PCIe a 4 corsie Intel Iris Graphics 6100 integrato','Macbook Pro',NULL,1300,1,NULL,NULL,NULL,'technology','/assets/img/product03.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (11,'Sony','Black','Sony 1294 – 9064 – Xperia Z4 Tablet Black WiFi with bkb50 keyboard','Sony',NULL,350,1,NULL,NULL,NULL,'technology','/assets/img/product04.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (12,'MSI','Black/Red','Intel Core i5 10300H e scheda grafica GeForce RTX 3060 Max-Q di NVIDIA (16 GB RAM e 512 GB SSD). ','MSI',NULL,1300,1,NULL,NULL,NULL,'technology','/assets/img/product06.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (13,'Samsung','Silver','Samsung A5 2016, Smartphone LTE / UMTS / HSDPA / Quadri Band, Sistema Operativo: Android 4.4 (KitKat), Memoria: 16 GB Espandibile con MicroSD fino a 64 GB, Display: 5,0\"Fotocamera: 13 MP','Samsung Galaxy',NULL,550,1,NULL,NULL,NULL,'technology','/assets/img/product07.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (14,'Asus','Black','Notebook Asus Portatile Pc Display da 15.6\"Windows 10 Pro e CPU INTEL','Asus KK6769',NULL,1200,1,NULL,NULL,NULL,'technology','/assets/img/product08.png',58);
INSERT INTO `products` (`id`,`brand`,`color`,`description`,`name`,`pics`,`price`,`quantity`,`size`,`upload_time`,`subcategory_id`,`category`,`image`,`user_id`) VALUES (15,'Lagostina','Silver','Acciaio Inox 18/10','Silverware',NULL,3000,1,'',NULL,NULL,'cook','/assets/img/cook.png',58);
